### PR TITLE
Strip python source code to reduce size

### PR DESCRIPTION
**Pull request by nuwang**
Stripping python source from the site-packages folder saves ~125MB. I don't know whether there's a a better way to do this, but for wheels, there doesn't seem to be an option for installing compiled code only. Maybe @natefoo knows? ~~The other potential ill-effect of losing the source is that shell executable python scripts must now be executed through the python interpreter, not directly through bash, but this is probably not an issue?~~ Executable python scripts seem to be a non-issue, since they reside in .venv/bin, not in .venv/site-packages.

### CODE REVIEW

**Comment by jdavcs** [comment]
Just when I thought we couldn't reduce it any further :-)

**Comment by natefoo** [comment]
My only concern here is that tracebacks won't actually be useful anymore, will they? I'm pretty sure the interpreter needs the original source to generate at least the line contents, and maybe the line numbers and function names?

Is there any chance the bulk of that 125MB was only a small handful of files?

**Comment by nuwang** [comment]
@natefoo I didn't think of that at all. You're right, I think we should roll this change back.

**Comment by jdavcs** [comment]
Reverted. Sorry - I must've rushed the merge in the first place. I didn't think of tracebacks either.

**Comment by nuwang** [comment]
Just for ref, this is the difference between a stack trace with and without source.
With source:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    main()
  File "test.py", line 10, in main
    func2()
  File "test.py", line 7, in func2
    func("World")
  File "test.py", line 3, in func
    raise Exception("Got invalid param %s" % hello)
Exception: Got invalid param World
```

Without:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
  File "test.py", line 10, in main
  File "test.py", line 7, in func2
  File "test.py", line 3, in func
Exception: Got invalid param World
```
As you suspected, we lose the source line (and possibly more if we perform some kind of minimisation/mangling on the byte code), which is pretty bad from a debugging perspective.

**Pull request merged**
