### PR TITLE
Improve handling of conditional requirements to match Galaxy

### PR DESCRIPTION
**Pull request by nuwang**
This PR enables k8s specific requirements to be handled in a more robust way, respecting any constraints specified in Galaxy's conditional requirements file.

### CODE REVIEW

**Comment by nuwang** [comment]
After setting `galaxy_manage_gravity` to False the container builds correctly, and can be started up and serves Galaxy as expected. So this PR looks good to go!

**Comment by nuwang** [comment]
And this is what the k8s-requirements.txt file looks like:

```bash
galaxy@d44d9b401c46:/galaxy/server/lib/galaxy/dependencies$ cat k8s-requirements.txt
-r pinned-requirements.txt
psycopg2-binary==2.9.5
pykube==0.15.0
total-perspective-vortex<3
```

**Comment by afgane** [comment]
When I was looking to resume image builds a couple of weeks ago, I had to disable systemd handler as well: https://github.com/galaxyproject/galaxy-docker-k8s/commit/b7751ff175acc69221f4769ea5052223309114b1#diff-6377f8a1937054624eac73b02854e7f99081cb731582fcecd1b435c5ded73120R18

Is the Galaxy role working without it now?

Also, this will work for 23.0 and TPV <3. What about 22.05?

**Comment by nuwang** [comment]
On 22.05, it will pickup total-perspective-vortex<2 from the requirements, so all should be well.

It didn't complain about systemd, started up and served the web ui.

**Pull request merged**
