### PR TITLE
Switched to python 3

### LINKED ISSUE #9: Switch to Python 3 for 19.09
Switch to python 3 because it makes more sense to get that fined tuned. I'd suggest a rebuild of 19.09.

### PR DESCRIPTION
**Pull request by nuwang**
Closes: https://github.com/CloudVE/galaxy-docker-k8s/issues/9

Surprisingly, there's a 5MB reduction in size: https://hub.docker.com/r/nuwang/galaxy-k8s/tags

### CODE REVIEW

**Comment by nuwang** [comment]
This is probably not working as expected. It looks like ansible-galaxy is still fixed to 2.7:
https://github.com/galaxyproject/ansible-galaxy/blob/02275ebeed017ac3c04f0406818ded4a284ca3d6/tasks/virtualenv.yml#L13

**Comment by nuwang** [comment]
Needs a complementary change in ansible-galaxy: https://github.com/galaxyproject/ansible-galaxy/pull/91

**Comment by mvdbeek** [comment]
That looks good to me, any reason to not go ahead with the switch ?

**Comment by afgane** [comment]
We'll just leave this for post-GVL5 release and hence Galaxy 20.05 to give the tools that default to using the Galaxy container a bit more time.

**Comment by mvdbeek** [comment]
Fair enough, I was hoping I could integrate this into integration testing. Could we perhaps have two variants, one with python 2 and one with 3?

Is there a specific set of tools you're concerned about? And could this be addressed with a python 2 default container?

**Comment by afgane** [comment]
Our fallback for all the converters and tools that ship with Galaxy is just the Galaxy container, which seems to be working fine. Our aim is to have the GVL5 release complete by the end of the month. At this point we're really just focusing on getting a representative set of training workflows to work out of the box and as soon as that gets a green light, we'd like to make the release. Adding another variable this late in the cycle seems like too much risk. So how about we merge this as soon as the the release happens? Does that timeline sound reasonable vs. making another branch/container?

**Comment by mvdbeek** [comment]
Sure, that will be fine!

**Pull request merged**
