### PR TITLE
Do not set conda_auto_init in the config.

### PR DESCRIPTION
**Pull request by rhpvorderman**
See https://github.com/galaxyproject/galaxy/pull/12200

### CODE REVIEW

**Comment by nuwang** [comment]
Makes sense, thanks!

**Comment by rhpvorderman** [comment]
@nuwang Could you push the latest dev container to the docker hub? Then I can add that to this PR: https://github.com/galaxyproject/ephemeris/pull/172
It now uses a custom image I maintain, but I rather have ephemeris tested on an official galaxy container.

**Comment by nuwang** [comment]
@rhpvorderman Have triggered a build: https://hub.docker.com/repository/docker/galaxy/galaxy-min/general

**Comment by rhpvorderman** [comment]
Thank you!

**Pull request merged**
