### PR TITLE
Pin TPV

### PR DESCRIPTION
**Pull request by ksuderman**
TPV 2.0 introduces breaking changes so we should pin this to known working versions until 23.0

### CODE REVIEW

**Comment by afgane** [comment]
I think this needs to be made conditional based on the version of the Galaxy being built because this same playbook is already being used to build 23.0 images (https://quay.io/repository/galaxyproject/galaxy-min?tab=tags), and shouldn't pin it for that image.

**Comment by nuwang** [comment]
Please, any upgrades we need to make are trivial, so I think we can leave unpinned and just update the values file?

**Comment by pcm32** [comment]
This is breaking our setup @nuwang , we have one deployment with 22.05 that is using tpv 1.x and another deployment (same versions of helm chart and galaxy container) with tpv 2.x installed. As a result, the YAML files that we have are not read correctly and our job submission doesn't work of the later setup.

**Comment by pcm32** [comment]
I would argue that 2.x installations of TPV should only make it to 23.0 build images.

**Comment by pcm32** [comment]
Both deployments are supposed to look the same (one is dev, one is prod, only difference is meant to be the hardware size), and we hope to be able to do this by pinning versions.

**Comment by pcm32** [comment]
> I think this needs to be made conditional based on the version of the Galaxy being built because this same playbook is already being used to build 23.0 images (https://quay.io/repository/galaxyproject/galaxy-min?tab=tags), and shouldn't pin it for that image.

I agree, maybe we can have release branches here?

**Comment by nuwang** [comment]
@pcm32 Saw the discussion on gitter and understand the problem now. Agree with what you say, the solution appears to be to make tpv > 2 only for 23.0 onwards.

**Review by nuwang — APPROVED** [review]

**Comment by ksuderman** [comment]
I agree with Enis that we should make this conditional.  However, I'm not sure how we want to do that here.

**Comment by pcm32** [comment]
Can we have at least a first non elegant solution? we need that 22.05 min image back in shape :-) .

**Comment by pcm32** [comment]
I tried pulling the older image via sha256, but it is not available from quay anymore, and I have no idea how to retrieve a container from inside the kubernetes nodes now that they use containerd directly. I couldn't find any of the containerd interface applications installed and I don't want to mess with our nodes software installation which is done all automatic.

**Comment by afgane** [comment]
Looks like we can pass the IMAGE_TAG var from the Galaxy repo https://github.com/galaxyproject/galaxy/blob/076a695afd90d9ad7b140aabd02871422496c770/.k8s_ci.Dockerfile#L75 and should be able to use that then.

**Comment by pcm32** [comment]
Thanks guys! Do we need then a PR to the galaxy 22.05 release branch so that the 22.05 container gets recreated?

**Comment by afgane** [comment]
But for the time being, let's build this so you're not stuck Pablo. I've initiated the Action run on the Galaxy side so hopefully in a few mins, we'll have a 22.05 image like earlier.

**Comment by nuwang** [comment]
This fix appears to be in the wrong branch. It should be in the v3.0.0 branch, which is what the .k8s_ci.Dockefile is referring to.

We can then create a v4.0.0 branch, and update the dockerfile to point to that: https://github.com/galaxyproject/galaxy/blob/dev/.k8s_ci.Dockerfile#L25
so that future builds are handled correctly.

For my part, I had completely forgotten that we had planned to use branches to handle these kinds of changes in a safe way.

Have made two PRs that should improve:
https://github.com/galaxyproject/galaxy/pull/15647
https://github.com/galaxyproject/galaxy-docker-k8s/pull/35

**Pull request merged**
